# -*- mode: ruby -*-
# vi: set ft=ruby :
VM_ID = "cluster3"
IP_NW = "192.168.13."

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

# Single Control-Plane node  
  config.vm.define "#{VM_ID}-master1" do |node|
      node.vm.provider "virtualbox" do |vb|
          vb.name = "#{VM_ID}-master"
          vb.memory = 1024
          vb.cpus = 2
      end
      node.vm.hostname = "#{VM_ID}-master1"
      node.vm.network :private_network, ip: IP_NW + "10"

      node.vm.provision "setup-hosts", :type => "shell", :path => "scripts/setup-hosts.sh" do |s|
        s.args = ["enp0s8"]
      end
      node.vm.provision "setup-dns", type: "shell", :path => "scripts/update-dns.sh"
      node.vm.provision "install-docker", type: "shell", :path => "scripts/install-docker.sh"
  end

# Worker machine
  config.vm.define "#{VM_ID}-worker1" do |node|
    node.vm.provider "virtualbox" do |vb|
        vb.name = "#{VM_ID}-worker1"
        vb.memory = 2048
        vb.cpus = 2
    end
    node.vm.hostname = "#{VM_ID}-worker1"
    node.vm.network :private_network, ip: IP_NW + "11"

    node.vm.provision "setup-hosts", :type => "shell", :path => "scripts/setup-hosts.sh" do |s|
      s.args = ["enp0s8"]
    end
        
    node.vm.provision "setup-dns", type: "shell", :path => "scripts/update-dns.sh"
    node.vm.provision "install-docker", type: "shell", :path => "scripts/install-docker.sh"
  end
end
